# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: SBAUG - Santa Barbara Apple Users Group

description: > # this means to ignore newlines until "baseurl:"
  The Santa Barbara Apple Users Group has been around since 1984.  We get together regularly to talk about our computers and help each other get the most out of our Apple products.
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://fast.sbaug.org" # the base hostname & protocol for your site
twitter_username: sbmug
github_username:  sbaug

# Build settings
markdown: kramdown
